### ISSUE TITLE
How to download Monterey 12.2.1 recovery image?

### ISSUE THREAD

**Issue by asfsha** [yahgoo/Hackintosh-HP-9470m-Opencore-Monterey-1600x900-Broadcom-WiFi#3]
I know the macrecovery.py method, but how to make it install 12.2.1 instead of the latest Monterey?

**Comment by yahgoo** [comment]
I have not used this method. Download it like this https://tipsmake.com/how-to-download-the-macos-12-monterey-installer-with-gibmacos and clean install Monterey
